/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stripe.playground;
import com.stripe.Stripe;
import com.stripe.exception.StripeException;
import com.stripe.model.Customer;
import com.stripe.net.RequestOptions;
import com.stripe.param.CustomerCreateParams;
import com.stripe.param.common.EmptyParam;


public class App {
    public static void main(String[] args) {
        Stripe.apiKey = "sk_test_...";

        CustomerCreateParams params =
            CustomerCreateParams
                .builder()
                .setAddress(
                    CustomerCreateParams.Address.builder().
                        setCity("Jakarta").build())
                .build();

        try {
            Customer customer = Customer.create(params);
            System.out.println(customer);
        } catch (StripeException e) {
            e.printStackTrace();
        }
    }
}
